FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -ldflags="-s -w" -o client ./cmd/client

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/client .
ENTRYPOINT ["./client"]
